# Generated by Django 3.1.4 on 2021-04-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=255)),
                ('detail_type', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='gallery_cars')),
            ],
        ),
    ]
