# Generated by Django 3.1.4 on 2021-04-29 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='date_added',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
