# Generated by Django 3.1.4 on 2021-05-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_galleryimage_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('stage_1', 'Stage 1 - Exterior Detail'), ('stage_2', 'Stage 2 - Interior Detail'), ('stage_3', 'Stage 1 - Full Detail'), ('stage_1', 'Stage 1 - Exterior Detail')], default='stage_1', max_length=18)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='detail_type',
            field=models.CharField(choices=[('stage_1', 'Stage 1'), ('stage_2', 'Stage 2'), ('interior_detail', 'Interior Detail'), ('snow_foamed', 'Snow Foamed'), ('other', 'Other')], default='other', max_length=18),
        ),
    ]
